// export { default as goutte } from './goutte.png'
// export { default as goutteResp } from './goutteResp.png'
// export { default as goutteGm } from './goutteGm.png'
// export { default as huile } from './huile.png'
// export { default as force } from './force.png'
export { default as logo } from './logoSvg.svg'
export { default as logoDark } from './logoDarkSvg.svg'
export { default as femme } from './femme.png'
export { default as homme } from './homme.png'
// export { default as ricin } from './ricin1.png'
// export { default as tamanu } from './tamanu1.png'
// export { default as baobab } from './baobab1.png'
// export { default as sesame } from './sesame1.png'
// export { default as coeur } from './coeur.png'
// export { default as hair } from './hair.png'
// export { default as creme } from './creme.png'
// export { default as platre } from './platre.png'
export { default as bitmap } from './bitmap.svg'
export const baobab = 'https://i.imgur.com/8Dnb96p.png'
export const ricin = 'https://i.imgur.com/abF07zC.png'
export const coeur = 'https://i.imgur.com/2EseJwV.png'
export const creme = 'https://i.imgur.com/5L0p9Fd.png'
export const force = 'https://i.imgur.com/U7pmCnk.png' 
export const goutte = 'https://i.imgur.com/0yJq034.png'
export const goutteGm = 'https://i.imgur.com/7dLPhT9.png'
export const goutteResp = 'https://i.imgur.com/nf3Ez4O.png'
export const hair = 'https://i.imgur.com/Gay6kRE.png'
export const huile = 'https://i.imgur.com/SFSGe95.jpeg'
export const platre = 'https://i.imgur.com/DNs5Xwj.png'
export const sesame = 'https://i.imgur.com/pzh1VER.png'
export const tamanu = 'https://i.imgur.com/YpyOo29.png'
